name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
      - name: Baixar cod
        uses: actions/checkout@v4
      
      - name: Config python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Testar
        run: pytest
      
      - name: Build image
        run: docker build -t lacreisaudeapi:ci .

      - name: Subir API
        run: docker run -d --name lacreisaude-api -p 8000:8000 lacreisaudeapi:ci

      - name: Status container
        run: |
          docker ps -a
          docker logs lacreisaude-api

      - name: Valida API
        run: curl http://localhost:8000/status      
